import yaml

# Emulate a user configuring the module.
module_config = dict()
with open(workflow.source_path("../../config/config.yaml"), "r") as f:
    module_config["module_co2stop_cdr"] = yaml.safe_load(f.read())


# Import the module and configure it.
# `snakefile:` specifies the module. It can use file paths and special github(...) / gitlab(...) markers
# `prefix:` re-routes all input/output paths of the module, helping to avoid file conflicts.
module module_co2stop_cdr:
    snakefile:
        "../../workflow/Snakefile"
    config:
        module_config["module_co2stop_cdr"]
    prefix:
        "results/integration_test/"


# rename all module rules with a prefix, to avoid naming conflicts.
use rule * from module_co2stop_cdr as module_co2stop_cdr_*


FILES = ["aquifer"]


# Request something from the module
rule all:
    message:
        "A generic test case for your module."
    default_target: True
    input:
        expand("results/integration_test/results/BALK/medium/{cdr}.png", cdr=FILES),
